const {test, expect} = require('@playwright/test');
const {readFile} = require('node:fs/promises');
const {gunzipSync} = require('node:zlib');

test('任务中台：全宽机器泳道、线性缩放、原生下载与未知任务处理', async ({page, browserName}, testInfo) => {
  const pageErrors = [], policyErrors = [];
  page.on('pageerror', error => pageErrors.push(error.message));
  page.on('console', message => { if (/Content Security Policy|violates.*directive/i.test(message.text())) policyErrors.push(message.text()); });
  await page.goto('/?tasks=1');
  await expect(page.locator('#task-filter')).toHaveValue('running');
  await page.locator('#task-filter').selectOption('all');
  await expect(page.locator('.task-machine-group')).toHaveCount(16);
  await expect(page.locator('.task-lane')).toHaveCount(33);
  await expect(page.locator('#task-stats')).toContainText('16 注册机器');
  await expect(page.locator('#task-count')).toContainText('33 条任务');
  const panel = await page.locator('#task-panel').boundingBox();
  expect(panel.width).toBeGreaterThan(2450);
  await expect(page.locator('.task-no-jobs')).toHaveCount(13);
  await page.locator('#task-scope').selectOption('machine');
  await expect(page.locator('#task-machine option')).toHaveCount(16);
  await page.locator('#task-machine').selectOption('machine-02');
  await expect(page.locator('#task-submit')).toBeDisabled();
  await page.locator('#task-machine').selectOption('machine-15');
  await expect(page.locator('#task-submit')).toBeEnabled();
  await page.getByRole('button',{name:'收起机器',exact:true}).click();
  await expect(page.locator('.task-lane')).toHaveCount(0);
  await expect(page.locator('.task-machine-group')).toHaveCount(16);
  await page.getByRole('button',{name:'展开机器 测试机器 00',exact:true}).click();
  await expect(page.locator('.task-lane')).toHaveCount(11);
  await page.getByRole('button',{name:'展开机器 测试机器 01',exact:true}).click();
  await page.getByRole('button',{name:'展开机器 测试机器 02',exact:true}).click();
  const board = page.locator('#task-board');
  const rangeBefore = await page.locator('#task-range').textContent();
  const duration = page.locator('.task-duration[data-task-id="history-00"]');
  const before = await duration.boundingBox();
  const box = await board.boundingBox();
  await page.mouse.move(box.x + 260, box.y + 140);
  await page.mouse.wheel(0,-320);
  await expect(page.locator('#task-range')).not.toHaveText(rangeBefore);
  const after = await duration.boundingBox();
  expect(after.width).toBeGreaterThan(before.width);
  // Auto-refresh must preserve the user's zoom, even as running-task time grows.
  const zoomed = await page.locator('#task-range').textContent();
  await page.getByRole('button',{name:'刷新',exact:true}).click();
  await expect(page.locator('#task-range')).toHaveText(zoomed);
  await page.getByRole('button',{name:'全局',exact:true}).click();
  await page.locator('.task-row-title[data-task-id="history-00"]').click();
  await expect(page.locator('#task-detail')).toContainText('history-00');
  await expect(page.locator('#task-detail')).toContainText('全部里程碑（4）');
  const requestPromise = page.context().waitForEvent('request', request => request.url().includes('/api/tasks/archive'));
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button',{name:'下载结果包',exact:true}).click();
  const request = await requestPromise;
  expect(request.method()).toBe('POST');
  const headers = await request.allHeaders();
  expect(headers.origin).toBe('http://127.0.0.1:18767');
  expect(request.url()).not.toContain('token');
  const download = await downloadPromise;
  expect(await download.failure()).toBeNull();
  expect(download.suggestedFilename()).toBe('history-00.tar.gz');
  const archive = await readFile(await download.path());
  expect(gunzipSync(archive).toString()).toContain('local browser fixture only');
  // Each browser has its own unknown task so all share the deterministic fixture.
  const index = {chromium:0,firefox:1,webkit:2}[browserName];
  const id = `unknown-${index}`;
  await page.locator(`.task-row-title[data-task-id="${id}"]`).click();
  await page.getByRole('button',{name:'重新探测远端状态'}).click();
  await expect(page.locator('#task-message')).toContainText('探测完成');
  await expect(page.locator('#task-detail .task-status')).toHaveText('结果未知');
  await page.getByRole('button',{name:'读取日志末尾'}).click();
  await expect(page.locator('.task-log-pair')).toContainText('progress');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button',{name:'已核实远端停止，解除占用…'}).click();
  await expect(page.locator('#task-detail .task-status')).toHaveText('结果未知');
  const statsBefore = await page.locator('#task-stats').textContent();
  const readyBefore = Number(statsBefore.match(/(\d+) ready/)[1]);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button',{name:'已核实远端停止，解除占用…'}).click();
  await expect(page.locator('#task-detail .task-status')).toHaveText('人工解除');
  await expect(page.locator('#task-stats')).toContainText(`${readyBefore + 1} ready`);
  await expect(page.locator('.task-machine-group')).toHaveCount(16);
  await page.getByRole('button',{name:'全局',exact:true}).click();
  await board.evaluate(element => { element.scrollTop = 0; });
  // Playwright's WebKit screenshot helper injects a stylesheet that this app's
  // strict CSP blocks. Keep UI/CSP assertions in all engines; capture with Chromium/Firefox.
  if (browserName !== 'webkit') await page.screenshot({path:testInfo.outputPath('task-dashboard.png'),fullPage:true});
  await page.setViewportSize({width:720,height:900});
  await expect(page.locator('#task-panel')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(720);
  expect(pageErrors).toEqual([]);
  expect(policyErrors).toEqual([]);
});
