'use strict';
(() => {
 const dialog=document.querySelector('#execution-dialog'),el=id=>document.querySelector('#execution-'+id);
 const selected=new Set();let machines=[],profiles=[],prepared=null,submitting=false,jobID='',jobRunning=false,jobQuery=0,polling=false;
 const words={queued:'等待执行',running:'连接 / 执行中',succeeded:'成功',failed:'失败',unknown:'结果未知',cancelled:'未执行'};
 const fail=e=>{el('error').textContent=e.message||String(e)};
 const filter=()=>{const value=el('filter').value.trim().toLowerCase();return machines.filter(m=>[m.name,m.host,m.group].join(' ').toLowerCase().includes(value))};
 const user=m=>profiles.find(p=>p.id===m.profileId)?.username||(demo?'root':'');
 function count(){el('count').textContent=`${demo?'演示预览 · 不执行 SSH · ':''}已选 ${selected.size} / ${machines.length} 台（筛选不会清除已选项）`}
 function renderMachines(){el('machines').innerHTML=filter().map(m=>`<label><input type="checkbox" data-execution-machine="${esc(m.id)}" ${selected.has(m.id)?'checked':''}><span>${esc(m.name)}<small>${esc(user(m))}@${esc(m.host)}:${m.port} · ${esc(m.group||'未分组')}</small></span></label>`).join('')||'<p>没有可选机器，请在管理机器中配置并启用。</p>';count()}
 function edit(){prepared=null;el('review-panel').hidden=true;el('edit').hidden=false;el('error').textContent=''}
 function review(){el('error').textContent='';const shell=el('shell').value.trim();if(!shell||!selected.size){fail('请选择机器并填写单次命令');return}if(/^(?:\/[^\s]+\/)?watch(?:\s|$)/.test(shell)){fail('这里是一次性执行，请去掉 watch 前缀');return}
  prepared={id:crypto.randomUUID(),shell,targets:machines.filter(m=>selected.has(m.id)).map(m=>({id:m.id,host:m.host,port:m.port,username:user(m)}))};
  el('review-command').textContent=shell;el('review-targets').innerHTML=prepared.targets.map(t=>`<li>${esc(machines.find(m=>m.id===t.id).name)} · ${esc(t.username)}@${esc(t.host)}:${t.port}</li>`).join('');el('submit').textContent=`在 ${prepared.targets.length} 台机器上执行一次`;el('edit').hidden=true;el('review-panel').hidden=false;
 }
 function renderJob(job){jobID=job.id;jobRunning=!job.finishedAt;const completed=job.results.filter(r=>!['queued','running'].includes(r.status)).length;const expanded=new Set([...el('results').querySelectorAll('details[open]')].map(d=>d.dataset.target));el('results').innerHTML=`<h3>${job.finishedAt?'本批已完成':'执行中'} · ${completed}/${job.results.length}</h3><pre>${esc(job.shell)}</pre><p>编号 ${esc(job.id)} · ${new Date(job.createdAt).toLocaleString('zh-CN')}。非零退出码按失败显示；例如 pkill 未匹配到进程通常返回 1。结果仅保留本次程序运行的最近 5 批。</p>${job.results.map(item=>{const r=item.result;return `<details class="execution-result" data-target="${esc(item.target.id)}" ${expanded.has(item.target.id)||item.status==='unknown'||(job.results.length===1&&job.finishedAt)?'open':''}><summary>${esc(item.name)} · ${esc(item.target.username)}@${esc(item.target.host)}:${item.target.port} · <b class="${item.status==='succeeded'?'execution-ok':item.status==='unknown'?'execution-unknown':''}">${words[item.status]}</b>${r.exitCode!==null?' · 退出码 '+r.exitCode:''}</summary>${r.error||r.warning?`<p>${esc(r.error||r.warning)}</p>`:''}<pre>${esc(r.stdout||'[stdout 为空]')}</pre>${r.stderr?`<pre>stderr:\n${esc(r.stderr)}</pre>`:''}${r.truncated?'<p>输出已截断（每条流最多保留 16 KiB）。</p>':''}</details>`}).join('')}`}
 async function jobs(){const generation=++jobQuery;if(demo){el('jobs').innerHTML='';return}const list=await api('executions');if(generation!==jobQuery)return;const old=jobID;el('jobs').innerHTML=list.map(job=>`<option value="${esc(job.id)}">${new Date(job.createdAt).toLocaleTimeString('zh-CN')} · ${job.count} 台 · ${job.finishedAt?'已完成':'运行中'}</option>`).join('');const job=list.find(j=>j.id===old)||list[0];if(job){el('jobs').value=job.id;const detail=await api('executions?id='+encodeURIComponent(job.id));if(generation===jobQuery)renderJob(detail)}}
 async function submit(){if(submitting||!prepared)return;if(demo){fail('演示模式不执行 SSH 命令，请退出演示后使用');return}submitting=true;el('submit').disabled=true;el('back').disabled=true;el('error').textContent='';try{const job=await api('executions','POST',prepared);prepared=null;el('review-panel').hidden=true;el('edit').hidden=false;renderJob(job);await jobs()}catch(e){fail(`${e.message}。若请求中断，可再次点击同一按钮查询/提交同一执行编号，不会重复执行。`)}finally{submitting=false;el('submit').disabled=false;el('back').disabled=false}}
 el('btn').onclick=async()=>{dialog.showModal();try{if(!demo)await loadConfig();machines=config.machines.filter(m=>m.enabled);profiles=config.profiles;for(const id of selected)if(!machines.some(m=>m.id===id))selected.delete(id);if(!submitting)edit();renderMachines();await jobs()}catch(e){fail(e)}};
 el('close').onclick=()=>dialog.close();el('filter').oninput=renderMachines;
 el('machines').onchange=e=>{const id=e.target.dataset.executionMachine;if(!id)return;e.target.checked?selected.add(id):selected.delete(id);count()};
 el('select').onclick=()=>{filter().forEach(m=>selected.add(m.id));renderMachines()};el('clear').onclick=()=>{selected.clear();renderMachines()};
 el('template').onclick=()=>{const preset=el('preset').value,pattern=el('pattern').value.trim();if(preset==='custom'){el('shell').focus();return}if(!pattern){fail('先填写匹配表达式');return}const quoted="'"+pattern.replaceAll("'","'\"'\"'")+"'";el('shell').value=(preset==='pkill'?'pkill -f -- ':'pgrep -af -- ')+quoted;el('error').textContent=''};
 el('review').onclick=review;el('back').onclick=edit;el('submit').onclick=submit;
 el('refresh').onclick=()=>jobs().catch(fail);el('jobs').onchange=()=>{jobID=el('jobs').value;jobs().catch(fail)};
 setInterval(async()=>{if(!dialog.open||demo||polling||!jobID||!jobRunning)return;polling=true;try{const job=await api('executions?id='+encodeURIComponent(jobID));if(job.id===jobID)renderJob(job)}catch(e){fail(e)}finally{polling=false}},1500);
})();
