'use strict';
(() => {
 const panel=document.querySelector('#history-panel');
 let active=false,catalog={machines:[],commands:{}},rows=[],machinePage=0,selected=null,frames=[],frameIndex=0,playing=false,playTimer=null,request=0,detailRequest=0,selectionRequest=0,refreshing=false;
 const stamp=v=>new Date(v).toLocaleString('zh-CN',{hour12:false});
 const clock=v=>new Date(v).toLocaleTimeString('zh-CN',{hour12:false});
 const local=v=>{const d=new Date(v);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,19)};
 const q=values=>new URLSearchParams(values).toString();
 panel.innerHTML=`<div class="history-controls"><h2>历史记录 · 多机时间矩阵</h2><button id="history-record" class="primary">开始记录</button><button id="history-live">返回实时监控</button><span id="history-status"></span></div>
 <p>记录全部启用机器与正在运行的自定义指令，并附带 NPU、完整 ps -ef、进程工作目录。自定义指令在实时页添加/启停。浏览器关闭不影响后台记录；程序退出后停止，重启需重新开启。历史输出明文保存在本机 history 目录。</p>
 <div id="history-error" role="alert"></div><div class="history-controls"><label>起点 <input id="history-start" type="datetime-local" step="1"></label><label>范围 <select id="history-span"><option value="60">1 分钟</option><option value="300">5 分钟</option><option value="900">15 分钟</option><option value="3600" selected>1 小时</option></select></label><button id="history-back">前一时段</button><button id="history-forward">后一时段</button><button id="history-latest">最近记录</button><button id="history-refresh">刷新历史</button></div>
 <div class="history-controls"><label>指令 <select id="history-command"></select></label><label>本地规则 <select id="history-rule"><option value="none">仅记录，不判断</option><option value="contains">包含指定文本</option><option value="change">相比上一帧变化</option><option value="npu">同卡多个 PID（NPU 格式）</option></select></label><input id="history-keyword" maxlength="256" placeholder="匹配文本" aria-label="历史匹配文本" hidden><span>无 AI；命中规则不等于任务挤占</span><button id="history-machines-prev">上一组机器</button><span id="history-machine-page"></span><button id="history-machines-next">下一组机器</button></div>
 <p id="history-range"></p><div id="history-table-wrap"></div><div class="history-controls"><button id="history-frame-prev">上一帧</button><button id="history-play">播放</button><button id="history-frame-next">下一帧</button><select id="history-speed" aria-label="历史播放速度"><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select><input id="history-frames" aria-label="历史逐帧定位" type="range" min="0" max="0" value="0"><span id="history-frame-label">点击时间格查看记录</span><button id="history-zoom">放大选中分钟</button></div><div id="history-detail"></div>`;
 const el=id=>panel.querySelector('#history-'+id);
 el('start').value=local(Date.now()-3600000);
 const start=()=>new Date(el('start').value).toISOString();
 const span=()=>Number(el('span').value);
 const error=e=>{el('error').textContent=e.message||String(e)};
 function stop(){playing=false;clearTimeout(playTimer);el('play').textContent='播放'}
 async function status(){const s=await api('history/status');el('record').textContent=s.enabled?'停止记录':'开始记录';el('record').dataset.enabled=String(s.enabled);el('status').textContent=`${s.enabled?'● 记录中':'记录已停止'} · ${s.records} 份 · ${(s.bytes/1048576).toFixed(1)} / ${s.limitBytes/1048576} MiB · 保留 ${s.retentionDays} 天`;if(s.error)error(s.error)}
 async function catalogLoad(){catalog=await api('history/catalog');const previous=el('command').value;el('command').innerHTML=Object.entries(catalog.commands).map(([id,name])=>`<option value="${esc(id)}">${esc(name||id)}</option>`).join('');if(catalog.commands[previous])el('command').value=previous;else if(catalog.commands.npu)el('command').value='npu';machinePage=Math.min(machinePage,Math.max(0,Math.ceil(catalog.machines.length/16)-1))}
 async function loadMatrix(){
  const generation=++request;selectionRequest++;detailRequest++;stop();frames=[];selected=null;el('detail').innerHTML='';el('frame-label').textContent='点击时间格查看记录';el('frames').max='0';el('frames').value='0';el('error').textContent='';
  const machines=catalog.machines.slice(machinePage*16,(machinePage+1)*16),rule=el('rule').value,keyword=el('keyword').value;
  el('keyword').hidden=rule!=='contains';if(rule==='contains'&&!keyword){error('请输入匹配文本');return}
  el('machine-page').textContent=`${catalog.machines.length} 台 · 第 ${machinePage+1} / ${Math.max(1,Math.ceil(catalog.machines.length/16))} 组`;
  el('machines-prev').disabled=machinePage===0;el('machines-next').disabled=(machinePage+1)*16>=catalog.machines.length;
  if(!machines.length){el('table-wrap').textContent='还没有历史记录。点击“开始记录”后等待一轮采样；演示数据不会写入真实历史。';return}
  const from=start(),seconds=span(),columns=seconds===60?15:60;const data=await api('history/matrix?'+q({start:from,seconds,machines:machines.map(m=>m.id).join(','),command:el('command').value,rule,keyword}));if(generation!==request)return;rows=data;
  el('range').textContent=`${stamp(from)} — ${stamp(Date.parse(from)+seconds*1000)}。每格 ${seconds/columns} 秒，保留所有原始帧。橙色：规则命中；灰色：缺失/无法判断；深色：未记录。点击优先定位命中帧。`;
  el('table-wrap').innerHTML=`<table><thead><tr><th>机器 / 时间</th>${Array.from({length:columns},(_,i)=>`<th>${i%5===0?clock(Date.parse(from)+i*seconds/columns*1000):'·'}</th>`).join('')}</tr></thead><tbody>${machines.map((m,row)=>`<tr><th title="${esc(m.host)}">${esc(m.name||m.id)}</th>${data[row].cells.map((cell,column)=>`<td><button ${!cell.id?'disabled':''} data-history-cell="${row},${column}" class="${cell.hits?'hm-hit':cell.unknown?'hm-unknown':cell.count?'hm-good':'hm-empty'}" aria-label="${esc(m.name)} ${clock(Date.parse(from)+column*seconds/columns*1000)}" title="${cell.count} 帧；命中 ${cell.hits}；未知 ${cell.unknown}">${cell.hits?'!':cell.unknown?'?':cell.count?'·':'—'}</button></td>`).join('')}</tr>`).join('')}</tbody></table>`;
 }
 async function refresh(latest=false){if(refreshing)return;refreshing=true;try{await status();await catalogLoad();if(latest&&catalog.last&&!catalog.last.startsWith('0001'))el('start').value=local(Date.parse(catalog.last)-span()*1000+1000);await loadMatrix()}catch(e){error(e)}finally{refreshing=false}}
 function output(r){return !r?'<p>此轮未采集</p>':`<p>${esc(r.original||r.shell||'')} ${r.original!==r.shell?' → '+esc(r.shell):''}<br>${stamp(r.startedAt)} — ${stamp(r.endedAt)} · 退出码 ${r.exitCode??'未知'}${r.truncated?' · 输出被截断':''}</p>${r.error||r.warning?`<p>${esc(r.error||r.warning)}</p>`:''}<pre>${esc(r.stdout||'[stdout 为空]')}</pre>${r.stderr?`<pre>stderr:\n${esc(r.stderr)}</pre>`:''}`}
 function pidButtons(r){if(!r)return '';let active=false;const pids=[];for(const line of r.stdout.split('\n')){if(line.toLowerCase().includes('process id')){active=true;continue}if(!active)continue;const match=line.match(/^\|?\s*\d+\s+\d+\s+(\d+)\s+/);if(match&&!pids.includes(match[1]))pids.push(match[1])}return pids.length?`<div class="history-controls">${pids.map(pid=>`<button data-link-pid="${pid}">PID ${pid} → 目录</button>`).join('')}</div>`:''}
 function cwdRows(r,ps){if(!r)return '<p>此轮没有取得工作目录；不查询现在的机器补齐。</p>';const lines=r.stdout.split('\n');const boot=lines.find(l=>l.startsWith('BOOT\t'))?.slice(5)||'未知';let count=0;const table=lines.map(line=>{const [pid,ticks,value]=line.split('\t');if(!/^\d+$/.test(pid)||!value)return '';count++;let cwd=value;if(!value.startsWith('missing:')){try{cwd=new TextDecoder().decode(Uint8Array.from(atob(value),c=>c.charCodeAt(0)))}catch{cwd='目录编码无效'}}const process=(ps?.stdout||'').split('\n').find(l=>l.trim().split(/\s+/)[1]===pid)||'完整 ps 中没有此 PID（采集有时间差）';return `<tr data-history-pid="${pid}"><td><button>${pid}</button><br>starttime ${esc(ticks)}</td><td>${esc(cwd)}</td><td>${esc(process)}</td></tr>`}).join('');return `<p>boot ID：${esc(boot)} · ${count} 个进程。PID + starttime 在读取 cwd 前后校验；NPU/ps/cwd 不是原子快照。容器内外 PID 可能无法对应。${r.truncated||lines.some(l=>l.startsWith('LIMIT'))?'达到采集上限，仅显示部分目录。':''}</p>${r.error||r.warning?`<p>${esc(r.error||r.warning)}</p>`:''}<div class="history-proc"><table><thead><tr><th>PID / 身份</th><th>采样时工作目录</th><th>同轮 ps -ef 行</th></tr></thead><tbody>${table}</tbody></table></div>`}
 async function detail(id){const generation=++detailRequest;try{const record=await api('history/sample?'+q({id}));if(generation!==detailRequest)return;selected=record;const result=record.state.results||[],r=result.find(r=>r.commandId===el('command').value),ps=result.find(r=>r.commandId==='history-ps'),cwd=result.find(r=>r.commandId==='history-cwd');el('detail').innerHTML=`<div class="history-box"><h3>${esc(record.machineName)} · ${stamp(record.startedAt)}</h3><p>${esc(record.state.error||'')} · 本轮耗时 ${record.state.durationMs} ms</p>${output(r)}</div><div class="history-evidence"><div class="history-box"><h3>同轮 npu-smi info</h3>${output(result.find(r=>r.commandId==='npu'))}${pidButtons(result.find(r=>r.commandId==='npu'))}</div><div class="history-box"><h3>同轮完整 ps -ef</h3>${output(ps)}</div><div class="history-box history-wide"><h3>PID → 当时的工作目录</h3><label>定位 PID <input id="history-pid-search" inputmode="numeric" placeholder="输入 NPU 上的 PID"></label>${cwdRows(cwd,ps)}</div></div>`;frameIndex=Math.max(0,frames.findIndex(f=>f.id===id));el('frames').max=String(Math.max(0,frames.length-1));el('frames').value=String(frameIndex);el('frame-label').textContent=`${clock(record.startedAt)} · 第 ${frameIndex+1}/${frames.length} 帧`;el('frame-prev').disabled=frameIndex===0;el('frame-next').disabled=frameIndex>=frames.length-1}catch(e){error(e);stop()}}
 async function selectCell(row,column){stop();const serial=++selectionRequest;detailRequest++;const cell=rows[row].cells[column];if(!cell.id)return;const loaded=await api('history/frames?'+q({start:start(),seconds:span(),machine:rows[row].id}));if(serial!==selectionRequest)return;frames=loaded;await detail(cell.id)}
 async function move(delta){if(!frames.length)return;const index=frameIndex+delta;if(index<0||index>=frames.length){stop();return}await detail(frames[index].id)}
 function schedule(){if(!playing)return;if(frameIndex>=frames.length-1){stop();return}const delay=Math.max(100,Date.parse(frames[frameIndex+1].at)-Date.parse(frames[frameIndex].at))/Number(el('speed').value);playTimer=setTimeout(async()=>{await move(1);schedule()},delay)}
 async function toggle(){try{const enabled=el('record').dataset.enabled!=='true';if(demo&&enabled){error('请先退出演示并配置真实机器，再开启记录。');return}await api('history/status','POST',{enabled});await status()}catch(e){error(e)}}
 function close(){active=false;stop();request++;detailRequest++;selectionRequest++;document.body.classList.remove('history-mode');panel.hidden=true;document.querySelector('#history-btn').textContent='◷ 历史记录'}
 document.querySelector('#history-btn').onclick=()=>{if(active){close();return}active=true;document.body.classList.add('history-mode');panel.hidden=false;document.querySelector('#history-btn').textContent='返回实时';refresh(true)};
 el('live').onclick=close;el('record').onclick=toggle;el('refresh').onclick=()=>refresh();el('latest').onclick=()=>refresh(true);
 for(const id of ['start','span','command','rule','keyword'])el(id).onchange=()=>{detailRequest++;selected=null;frames=[];el('detail').innerHTML='';loadMatrix().catch(error)};
 el('back').onclick=()=>{el('start').value=local(Date.parse(start())-span()*1000);loadMatrix().catch(error)};el('forward').onclick=()=>{el('start').value=local(Date.parse(start())+span()*1000);loadMatrix().catch(error)};
 el('machines-prev').onclick=()=>{machinePage--;loadMatrix().catch(error)};el('machines-next').onclick=()=>{machinePage++;loadMatrix().catch(error)};
 panel.onclick=e=>{const pidButton=e.target.closest('[data-link-pid]');if(pidButton){const input=el('pid-search');if(input){input.value=pidButton.dataset.linkPid;panel.querySelectorAll('[data-history-pid]').forEach(row=>{row.hidden=row.dataset.historyPid!==input.value;row.classList.toggle('chosen',!row.hidden)});input.scrollIntoView({block:'center'});}}const cell=e.target.closest('[data-history-cell]');if(cell)selectCell(...cell.dataset.historyCell.split(',').map(Number)).catch(error);const row=e.target.closest('[data-history-pid]');if(row){panel.querySelectorAll('.chosen').forEach(x=>x.classList.remove('chosen'));row.classList.add('chosen')}};
 panel.oninput=e=>{if(e.target.id==='history-pid-search')panel.querySelectorAll('[data-history-pid]').forEach(row=>{row.hidden=!!e.target.value&&row.dataset.historyPid!==e.target.value})};
 el('frames').oninput=()=>{stop();if(frames.length)detail(frames[Number(el('frames').value)].id)};el('frame-prev').onclick=()=>{stop();move(-1)};el('frame-next').onclick=()=>{stop();move(1)};
 el('play').onclick=()=>{if(playing){stop();return}if(!frames.length)return;playing=true;el('play').textContent='暂停';schedule()};el('speed').onchange=()=>{clearTimeout(playTimer);schedule()};
 el('zoom').onclick=async()=>{if(!selected)return;const saved=selected;el('start').value=local(Math.floor(Date.parse(saved.startedAt)/60000)*60000);el('span').value='60';try{await loadMatrix();frames=await api('history/frames?'+q({start:start(),seconds:60,machine:saved.machineId}));await detail(saved.id)}catch(e){error(e)}};
 setInterval(()=>{if(active&&!document.hidden)status().catch(error)},5000);
})();
